
import React, { useState, useEffect } from 'react';
import { Message, Sender, MessageType, Product } from '../../types';
import { MOCK_ASTROLOGERS } from '../../constants';
import ProductCard from '../Shop/ProductCard';

interface MessageBubbleProps {
  message: Message;
  onUnlock: (messageId: string) => void;
  onPay?: (amount: number) => void;
  onAcceptCall?: (type: 'voice' | 'video') => void;
  onSubscribe?: () => void;
  onBuyProduct?: (product: Product) => void;
  userHasPremium: boolean;
  userName: string;
}

// Helper to render text without raw markdown symbols but with styling
const FormattedText: React.FC<{ text: string; isDrastic?: boolean }> = ({ text, isDrastic }) => {
  // 1. Handle Bold: **text** -> <strong>text</strong>
  // 2. Handle Bullets: * text -> <li>text</li>
  // 3. Handle Vastu Maps/ASCII: lines starting with + or |
  
  const lines = text.split('\n');
  
  // Logic to group consecutive ASCII map lines
  const renderLines = () => {
    const output = [];
    let asciiBuffer: string[] = [];

    const flushAscii = (keyPrefix: string) => {
        if (asciiBuffer.length > 0) {
            output.push(
                <div key={`${keyPrefix}-blueprint`} className="my-4 bg-mystic-950/80 border border-blue-400/30 rounded-lg p-4 font-mono text-xs md:text-sm text-blue-200 overflow-x-auto shadow-inner relative">
                    <div className="absolute top-1 right-2 text-[8px] uppercase tracking-widest text-blue-400 opacity-50">Vastu Blueprint</div>
                    <pre className="leading-none whitespace-pre">{asciiBuffer.join('\n')}</pre>
                </div>
            );
            asciiBuffer = [];
        }
    };

    lines.forEach((line, idx) => {
        const trimmed = line.trim();
        if (!trimmed) {
            flushAscii(`empty-${idx}`);
            return;
        }

        // Check if line is part of a map/grid
        const isMapLine = trimmed.startsWith('+') || trimmed.startsWith('|') || (trimmed.includes('---') && trimmed.includes('+'));

        if (isMapLine) {
            asciiBuffer.push(line);
            return;
        } else {
            flushAscii(`pre-${idx}`);
        }

        // Standard Text Rendering
        const isBullet = trimmed.startsWith('* ') || trimmed.startsWith('- ');
        const content = isBullet ? trimmed.substring(2) : trimmed;

        // Parse internal bolding
        const parts = content.split(/(\*\*.*?\*\*)/g);
        
        const renderedContent = parts.map((part, i) => {
          if (part.startsWith('**') && part.endsWith('**')) {
            // Enhanced gold highlighting
            return <strong key={i} className="text-gold-400 font-bold tracking-wide">{part.slice(2, -2)}</strong>;
          }
          return <span key={i}>{part}</span>;
        });

        output.push(
          <div key={idx} className={`flex ${isBullet ? 'gap-2 ml-2' : ''} ${isDrastic ? 'text-gold-300 italic font-medium' : ''}`}>
            {isBullet && <span className="text-gold-500 mt-1.5 text-[10px]">✦</span>}
            <p className={`leading-relaxed text-base ${isBullet ? 'flex-1' : ''}`}>
              {renderedContent}
            </p>
          </div>
        );
    });

    flushAscii('final');
    return output;
  };
  
  return (
    <div className="space-y-4">
      {renderLines()}
    </div>
  );
};

const MessageBubble: React.FC<MessageBubbleProps> = ({ message, onUnlock, onPay, onAcceptCall, onSubscribe, onBuyProduct, userHasPremium, userName }) => {
  const isUser = message.sender === Sender.USER;
  const isAstro = message.sender === Sender.ASTROLOGER;
  const isAI = message.sender === Sender.AI;
  
  const [isRevealed, setIsRevealed] = useState(false);
  const [isSpeaking, setIsSpeaking] = useState(false);

  // Stop speaking when component unmounts & preload voices
  useEffect(() => {
    // Pre-fetch voices to ensure they are loaded when user clicks speak
    window.speechSynthesis.getVoices();
    
    return () => {
      window.speechSynthesis.cancel();
    };
  }, []);

  // Parse Gist vs Deep Dive if generated by AI
  let gist = message.text;
  let deepDive = "";
  
  if (isAI && message.text.includes("Deep Dive:")) {
    const parts = message.text.split(/Deep Dive:/i);
    if (parts.length > 1) {
      gist = parts[0].trim();
      deepDive = parts[1].trim();
    }
  }

  const handleReveal = () => {
    onUnlock(message.id);
    setIsRevealed(true);
  };

  const handleSpeak = () => {
    // IMPORTANT: Always cancel before starting new speech to prevent queueing/stuck issues
    window.speechSynthesis.cancel();

    if (isSpeaking) {
        setIsSpeaking(false);
        return;
    }

    const fullText = isRevealed ? `${gist}. ${deepDive}` : gist;
    
    // Clean text for speech: remove *, emojis, and weird spacing
    const cleanText = fullText
        .replace(/\*/g, '') // remove asterisks
        .replace(/-/g, ' ') // remove dashes
        .replace(/\+/g, ' ') // remove plus signs from maps
        .replace(/\|/g, ' ') // remove pipes from maps
        .replace(/>/g, '') // remove blockquotes
        .replace(/[\u{1F600}-\u{1F64F}]/gu, "") // Emoticons
        .replace(/[\u{1F300}-\u{1F5FF}]/gu, "") // Symbols & Pictographs
        .replace(/Deep Dive:/gi, "")
        .replace(/\n/g, '. ');

    const utterance = new SpeechSynthesisUtterance(cleanText);
    
    // Voice Selection Logic for DEEP MALE VOICE
    const voices = window.speechSynthesis.getVoices();
    
    // Priority list for deep/male voices suitable for an Astrologer
    const preferredVoice = 
        voices.find(v => v.name.includes("Google English India") && v.name.includes("Male")) ||
        voices.find(v => v.name.includes("Google UK English Male")) || 
        voices.find(v => v.name.includes("Google US English Male")) || 
        voices.find(v => v.name.includes("Daniel")) || // iOS Low Pitch
        voices.find(v => v.name.includes("Rishi")) || 
        voices.find(v => v.name.toLowerCase().includes("male")) ||
        voices[0]; 

    if (preferredVoice) utterance.voice = preferredVoice;
    
    // Tuning for "Deep & Mystical"
    utterance.rate = 0.85;  // Slower than normal for gravitas
    utterance.pitch = 0.6;  // Significantly lower pitch (Default 1.0) for that "Guru" effect

    utterance.onend = () => setIsSpeaking(false);
    utterance.onerror = () => setIsSpeaking(false);
    
    window.speechSynthesis.speak(utterance);
    setIsSpeaking(true);
  };

  // Get Astrologer Image if applicable
  const astrologer = isAstro 
    ? MOCK_ASTROLOGERS.find(a => a.id === message.astrologerId) 
    : null;

  // Determine if content is accessible
  const isUnlocked = !message.isLocked || isRevealed || userHasPremium;

  // Render Special Message Types (Call Offer / Payment Request)
  const renderSpecialContent = () => {
    if (message.type === MessageType.CALL_OFFER) {
        return (
            <div className="bg-mystic-900/80 rounded-lg p-3 border border-green-500/50 flex flex-col items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-green-500/20 flex items-center justify-center text-green-400 animate-pulse">
                    {message.metadata?.callType === 'video' ? '📹' : '📞'}
                </div>
                <div className="text-center">
                    <p className="text-sm font-bold text-white">Incoming {message.metadata?.callType} Call</p>
                    <p className="text-xs text-mystic-400">Guru is inviting you to join</p>
                </div>
                <button 
                  onClick={() => onAcceptCall && onAcceptCall(message.metadata?.callType || 'voice')}
                  className="bg-green-600 hover:bg-green-500 text-white text-sm font-bold px-6 py-2 rounded-full shadow-lg transition-all hover:scale-105"
                >
                    Accept Call
                </button>
            </div>
        );
    }
    if (message.type === MessageType.PAYMENT_REQUEST) {
        return (
            <div className="bg-mystic-900/80 rounded-lg p-4 border border-gold-500/50 flex flex-col items-center gap-3 text-center">
                <div className="text-2xl">🕉️</div>
                <div>
                    <p className="text-sm font-bold text-gold-400">Dakshina Request</p>
                    <p className="text-xs text-mystic-300">Please offer dakshina to continue.</p>
                </div>
                <p className="text-xl font-bold text-white">₹{message.metadata?.amount}</p>
                <button 
                    onClick={() => onPay && onPay(message.metadata?.amount || 101)}
                    className="bg-gradient-to-r from-gold-600 to-gold-400 hover:from-gold-500 hover:to-gold-300 text-mystic-950 text-sm font-bold px-6 py-2 rounded-full shadow-lg transition-all hover:scale-105"
                >
                    Pay Now
                </button>
            </div>
        );
    }
    return null;
  };

  return (
    <div className={`flex w-full mb-6 items-end gap-3 ${isUser ? 'flex-row-reverse' : 'flex-row'}`}>
      
      {/* Avatar */}
      <div className="shrink-0 w-10 h-10 rounded-full shadow-lg border border-white/20 overflow-hidden relative group cursor-pointer">
        {isUser ? (
             <div className="w-full h-full bg-gradient-to-br from-violet-600 to-indigo-900 flex items-center justify-center text-white font-bold text-sm">
                {userName.charAt(0).toUpperCase()}
             </div>
        ) : isAstro ? (
            <img src={astrologer?.imageUrl} alt="Astro" className="w-full h-full object-cover" />
        ) : message.sender === Sender.SYSTEM ? (
            <div className="w-full h-full bg-gray-800 flex items-center justify-center text-xs">⚙️</div>
        ) : (
            <div className="w-full h-full bg-mystic-900 flex items-center justify-center text-lg">
                🔮
            </div>
        )}
      </div>

      {/* Bubble Container */}
      <div className="flex flex-col max-w-[90%] md:max-w-[85%] gap-2">
        <div 
            className={`relative rounded-2xl backdrop-blur-md shadow-lg border transition-all duration-300 ${
            isUser 
                ? 'bg-mystic-600/80 text-white rounded-br-none border-white/10 p-5' 
                : isAstro
                    ? 'bg-gradient-to-r from-mystic-800 to-mystic-900 text-mystic-50 rounded-bl-none border-gold-500/50 p-5'
                    : message.sender === Sender.SYSTEM
                        ? 'bg-gray-900/80 text-gray-300 text-xs border-gray-700 p-5'
                        : 'bg-mystic-800/95 text-mystic-100 rounded-bl-none border-white/10 pt-5 px-5 pb-2'
            }`}
        >
            {isAstro && (
                <div className="text-[10px] text-gold-400 font-serif uppercase tracking-widest mb-1">
                    {astrologer?.name || 'Astrologer'}
                </div>
            )}

            <div className="text-sm md:text-base font-sans">
            {message.type && message.type !== MessageType.TEXT ? (
                renderSpecialContent()
            ) : isUser || isAstro || message.sender === Sender.SYSTEM ? (
                <div className="whitespace-pre-wrap">{message.text}</div>
            ) : (
                <>
                <div className="mb-4">
                    <h4 className="text-xs font-bold text-mystic-400 uppercase tracking-widest mb-3 flex items-center gap-2 opacity-70">
                        <span>✨</span> Celestial Guidance
                    </h4>
                    
                    {/* Gist Rendering */}
                    <div className="text-mystic-100">
                        {(() => {
                            const lines = gist.split('\n').filter(l => l.trim() !== '');
                            const hasWarning = lines.length > 3; 
                            const mainContent = hasWarning ? lines.slice(0, -1).join('\n') : gist;
                            const warningContent = hasWarning ? lines[lines.length - 1] : null;

                            return (
                                <>
                                    <FormattedText text={mainContent} />
                                    {/* Highlighting the warning/cliffhanger */}
                                    {warningContent && (
                                        <div className="mt-6 pt-4 border-t border-white/5 bg-red-900/10 -mx-2 px-4 py-2 rounded">
                                            <p className="text-xs text-red-300 uppercase font-bold mb-1 tracking-widest">Cautionary Note</p>
                                            <FormattedText text={warningContent} isDrastic={true} />
                                        </div>
                                    )}
                                </>
                            );
                        })()}
                    </div>
                </div>
                
                {deepDive && (
                    <div className={`relative transition-all duration-700 ${!isUnlocked ? 'mt-4 pt-4 border-t border-white/10' : 'mt-2'}`}>
                    {/* If locked, show the header. If unlocked, "expand onto" previous text seamlessly */}
                    {!isUnlocked && (
                        <h4 className="text-gold-400 font-serif text-sm uppercase tracking-widest mb-3 flex items-center">
                        Full Vastu & Remedies
                        </h4>
                    )}
                    
                    <div className={`transition-all duration-1000 ${!isUnlocked ? 'filter blur-md select-none h-20 overflow-hidden opacity-50' : 'opacity-100'}`}>
                        {/* Visual spacer when unlocked to separate paragraphs slightly but keep flow */}
                        {isUnlocked && <div className="h-4 border-t border-white/5 w-10 mb-4 opacity-50"></div>}
                        <FormattedText text={deepDive} />
                    </div>

                    {!isUnlocked && (
                        <div className="absolute inset-0 flex flex-col items-center justify-center bg-gradient-to-b from-transparent to-mystic-900/90 rounded-b-xl z-10">
                        <p className="text-gold-200 text-xs mb-3 font-medium animate-pulse text-center px-4">
                            Unlock the Full Vastu Analysis, Visual Blueprint & Remedies
                        </p>
                        <button 
                            onClick={handleReveal}
                            className="group bg-gradient-to-r from-gold-600 to-gold-400 text-mystic-900 font-bold py-2 px-6 rounded-full shadow-lg hover:shadow-gold-500/20 transform hover:-translate-y-1 transition-all duration-300 flex items-center gap-2 text-sm"
                        >
                            <span>Unlock Full Reading</span>
                            <svg className="w-3 h-3 group-hover:rotate-12 transition-transform" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
                            </svg>
                        </button>
                        </div>
                    )}
                    </div>
                )}
                </>
            )}
            </div>
            
            {/* Footer Controls: TTS & Time */}
            <div className="mt-3 flex items-center justify-between">
                {/* Text to Speech Controls */}
                {!isUser && message.type !== MessageType.PAYMENT_REQUEST && message.type !== MessageType.CALL_OFFER && (
                    <button 
                        onClick={handleSpeak}
                        className={`p-1.5 rounded-full transition-colors ${isSpeaking ? 'bg-gold-500 text-mystic-900 animate-pulse' : 'text-mystic-500 hover:text-gold-400 hover:bg-white/5'}`}
                        title="Read Aloud"
                    >
                        {isSpeaking ? (
                            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 10a1 1 0 011-1h4a1 1 0 011 1v4a1 1 0 01-1 1h-4a1 1 0 01-1-1v-4z" /></svg>
                        ) : (
                            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.536 8.464a5 5 0 010 7.072m2.828-9.9a9 9 0 010 12.728M5.586 15H4a1 1 0 01-1-1v-4a1 1 0 011-1h1.586l4.707-4.707C10.923 3.663 12 4.109 12 5v14c0 .891-1.077 1.337-1.707.707L5.586 15z" /></svg>
                        )}
                    </button>
                )}

                <div className="text-[10px] text-white/40 uppercase tracking-widest font-serif flex items-center gap-1 ml-auto">
                    {message.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    {isUser && <span>✓</span>}
                </div>
            </div>

            {/* CTA for Membership - Only on AI messages and if user is NOT premium */}
            {!userHasPremium && isAI && (
                <div 
                    onClick={onSubscribe}
                    className="mt-4 -mx-5 -mb-2 bg-gradient-to-r from-mystic-900 to-mystic-950 border-t border-gold-500/20 py-3 px-5 rounded-b-2xl flex items-center justify-between cursor-pointer hover:bg-mystic-900 transition-colors group border-b border-white/5"
                >
                    <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded-full bg-gold-500/10 flex items-center justify-center text-lg border border-gold-500/30 group-hover:scale-110 transition-transform">
                        🔓
                    </div>
                    <div className="text-left">
                        <p className="text-xs font-bold text-gold-400 uppercase tracking-wider group-hover:text-gold-300">Unlock Full Potential</p>
                        <p className="text-[10px] text-mystic-400">Get Visual Vastu Maps & Remedies</p>
                    </div>
                    </div>
                    <div className="text-xs font-bold text-mystic-300 group-hover:text-white flex items-center gap-1">
                        Upgrade <span className="text-gold-500">→</span>
                    </div>
                </div>
            )}
        </div>

        {/* Suggested Product Card - Rendered OUTSIDE the bubble for cleaner UI */}
        {message.suggestedProducts && message.suggestedProducts.length > 0 && (
            <div className="animate-in slide-in-from-left-4 fade-in duration-500 mt-1">
                <div className="bg-gradient-to-r from-gold-900/40 to-mystic-900/40 border border-gold-500/30 rounded-xl p-3 max-w-xs">
                    <p className="text-xs text-gold-400 font-bold uppercase tracking-widest mb-2 flex items-center gap-1">
                        <span>🏷️</span> Recommended Remedy
                    </p>
                    {message.suggestedProducts.map(product => (
                        <div key={product.id} className="mb-2 last:mb-0">
                            <ProductCard product={product} onBuy={() => onBuyProduct && onBuyProduct(product)} isCompact={true} />
                        </div>
                    ))}
                </div>
            </div>
        )}
      </div>
    </div>
  );
};

export default MessageBubble;
